/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Conexion;
import Models.Detallevref;
import Models.Refacciones;
import Models.Facturavref;
import Models.Personas;
import static Models.Personas.celdaRfc;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.TableColumnModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Sakai
 */
public class conVentaRef extends javax.swing.JFrame {

    /**
     * Creates new form conVentaRef
     */
    public conVentaRef() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        showDataRef();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDataVRef = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(53, 100, 148));

        jButton1.setText("jButton1");

        jButton2.setText("Ventas");

        jButton3.setText("Ventas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jLabel1.setText("Busqueda por factura:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel2.setText("Busqueda por Nombre cliente:");

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTableDataVRef.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Factura", "Fecha", "Nombre", "Apellido", "# Refaccion", "Descripcion", "Precio", "Cantidad", "Subtotal", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDataVRef.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableDataVRef);
        if (jTableDataVRef.getColumnModel().getColumnCount() > 0) {
            jTableDataVRef.getColumnModel().getColumn(0).setResizable(false);
            jTableDataVRef.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableDataVRef.getColumnModel().getColumn(1).setResizable(false);
            jTableDataVRef.getColumnModel().getColumn(1).setPreferredWidth(50);
            jTableDataVRef.getColumnModel().getColumn(2).setResizable(false);
            jTableDataVRef.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableDataVRef.getColumnModel().getColumn(3).setResizable(false);
            jTableDataVRef.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableDataVRef.getColumnModel().getColumn(4).setResizable(false);
            jTableDataVRef.getColumnModel().getColumn(5).setResizable(false);
            jTableDataVRef.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableDataVRef.getColumnModel().getColumn(6).setResizable(false);
            jTableDataVRef.getColumnModel().getColumn(7).setResizable(false);
            jTableDataVRef.getColumnModel().getColumn(7).setPreferredWidth(40);
            jTableDataVRef.getColumnModel().getColumn(8).setResizable(false);
            jTableDataVRef.getColumnModel().getColumn(9).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Regresar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public ArrayList<Detallevref> listVRefacciones(){
        DefaultTableModel model = (DefaultTableModel)jTableDataVRef.getModel();
        ArrayList<Detallevref> listDetallevRef = new ArrayList<Detallevref>();
        Detallevref ventaref;
        Connection conn = Conexion.ConnectDB();
        if(celdaRfc == null){
            String query = "select facturavref.idfacturavref, fechavref, nombre, apellido,  refacciones.codRefaccion,descripcion, precio, cantidadref, (refacciones.preciopublico* cantidadref) as subtotal,((refacciones.preciopublico*cantidadref) + ((refacciones.preciopublico* cantidadref) * 0.16)) as total from personas inner join facturavref on personas.rfc=facturavref.rfc inner join detallevref on detallevref.idfacturavref=facturavref.idfacturavref inner join refacciones on detallevref.codRefaccion= refacciones.codRefaccion ";
            Statement st;
            ResultSet rs;
            try{
                st = conn.createStatement();
                rs = st.executeQuery(query);
                while(rs.next()){
                    ventaref = new Detallevref();
                    ventaref.setIdfacturavref(rs.getInt(1));
                    ventaref.setFechavref(rs.getString(2));
                    ventaref.setNombre(rs.getString(3));
                    ventaref.setApellido(rs.getString(4));
                    ventaref.setCodRefaccion(rs.getString(5));
                    ventaref.setDescripcion(rs.getString(6));
                    ventaref.setPrecio(rs.getDouble(7));       
                    ventaref.setCantidadref(rs.getInt(8));
                    ventaref.setSubtotal(rs.getDouble(9));
                    ventaref.setTotal(rs.getDouble(10));
                    listDetallevRef.add(ventaref);
                }
           }catch(Exception e){}
        }else {
           
             
            String query = "select facturavref.idfacturavref, fechavref, nombre, apellido,  refacciones.codRefaccion,descripcion, precio, cantidadref, (refacciones.preciopublico* cantidadref) as subtotal,((refacciones.preciopublico*cantidadref) + ((refacciones.preciopublico* cantidadref) * 0.16)) as total from personas inner join facturavref on personas.rfc=facturavref.rfc inner join detallevref on detallevref.idfacturavref=facturavref.idfacturavref inner join refacciones on detallevref.codRefaccion= refacciones.codRefaccion where personas.rfc = '"+Personas.celdaRfc+"'";
            Statement st;
            ResultSet rs;
            jTableDataVRef.removeColumn(jTableDataVRef.getColumnModel().getColumn(3));
            jTableDataVRef.removeColumn(jTableDataVRef.getColumnModel().getColumn(2));
            try{
                st = conn.createStatement();
                rs = st.executeQuery(query);
               
                while(rs.next()){
                    ventaref = new Detallevref();
                    ventaref.setIdfacturavref(rs.getInt(1));
                    ventaref.setFechavref(rs.getString(2));
                    ventaref.setNombre(rs.getString(3));
                    ventaref.setApellido(rs.getString(4));
                    ventaref.setCodRefaccion(rs.getString(5));
                    ventaref.setDescripcion(rs.getString(6));
                    ventaref.setPrecio(rs.getDouble(7));       
                    ventaref.setCantidadref(rs.getInt(8));
                    ventaref.setSubtotal(rs.getDouble(9));
                    ventaref.setTotal(rs.getDouble(10));
                    listDetallevRef.add(ventaref);
                }
                
                String nombre = rs.getString("nombre");
                String apellido = rs.getString("apellido");
                jTextField2.setText(nombre + " " + apellido);
            }catch(Exception e){}
            jLabel1.setText("Nombre de cliente: ");
            jTextField1.setVisible(false);
            
            //Remove column

            //End remove column
                    //Start testing to show name of clients
                Personas persona;
        String query2 = "select nombre, apellido from personas where rfc='"+celdaRfc+"'";
        Statement st2;
        ResultSet rs2;
        try{
            st2 = conn.createStatement();
            rs2 = st2.executeQuery(query2);
            if(rs2.next()){
                String nombre = rs2.getString("nombre");
                String apellido = rs2.getString("apellido");
                jLabel2.setText(nombre + " " + apellido);
                jLabel2.setSize(350, 20);
                jTextField2.setVisible(false);
                
            }
        }catch(Exception e){}
        //Ends Method
        }
        return listDetallevRef;
    }
    
        public void showDataRef(){
            ArrayList<Detallevref> listRef = listVRefacciones();
            DefaultTableModel model = (DefaultTableModel)jTableDataVRef.getModel();
            Object[] column = new Object[10];
            for(int i = 0; i < listRef.size(); i++){
                column[0] = listRef.get(i).getIdfacturavref()+" ";
                column[1] = listRef.get(i).getFechavref();
                column[2] = listRef.get(i).getNombre();
                column[3] = listRef.get(i).getApellido();
                column[4] = listRef.get(i).getCodRefaccion();
                column[5] = listRef.get(i).getDescripcion();
                column[6] = listRef.get(i).getPrecio();
                column[7] = listRef.get(i).getCantidadref();
                column[8] = listRef.get(i).getSubtotal();
                column[9] = listRef.get(i).getTotal();
                model.addRow(column);
            }
        }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Connection conn = Conexion.ConnectDB();
        try {
            conn.close();
            celdaRfc = null;
        } catch (SQLException ex) {
            Logger.getLogger(conVentaRef.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed
    TableRowSorter trsVRef;
    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        jTextField1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e){
                trsVRef.setRowFilter(RowFilter.regexFilter("(?i)"+jTextField1.getText(), 0));
            }
        });
        DefaultTableModel model = (DefaultTableModel)jTableDataVRef.getModel();
        trsVRef = new TableRowSorter(model);
        jTableDataVRef.setRowSorter(trsVRef);
    }//GEN-LAST:event_jTextField1KeyTyped

   
    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        jTextField2.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(final KeyEvent e){
                trsVRef.setRowFilter(RowFilter.regexFilter("(?i)"+jTextField2.getText(), 2,3));
            }
        });
        DefaultTableModel model = (DefaultTableModel)jTableDataVRef.getModel();
        trsVRef = new TableRowSorter(model);
        jTableDataVRef.setRowSorter(trsVRef);
    }//GEN-LAST:event_jTextField2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conVentaRef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conVentaRef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conVentaRef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conVentaRef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conVentaRef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDataVRef;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
